// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvy8AIrLGY7F98GxQL9KJ9q5tLbKUYgt0',
    appId: '1:255814710985:web:ad92450c2a8047bcb9bf18',
    messagingSenderId: '255814710985',
    projectId: 'journal-app-finals',
    authDomain: 'journal-app-finals.firebaseapp.com',
    storageBucket: 'journal-app-finals.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyW-lS0FyDglWYNBlK3nNuWfT_9ZNbV3c',
    appId: '1:255814710985:android:1450c6b90511ed51b9bf18',
    messagingSenderId: '255814710985',
    projectId: 'journal-app-finals',
    storageBucket: 'journal-app-finals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--QES7a5z7IWyxKkw0Tgc8hPSNBr2vOQ',
    appId: '1:255814710985:ios:b4e52de3f0b5b3a0b9bf18',
    messagingSenderId: '255814710985',
    projectId: 'journal-app-finals',
    storageBucket: 'journal-app-finals.appspot.com',
    iosBundleId: 'com.example.flutterJournalAppFinals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--QES7a5z7IWyxKkw0Tgc8hPSNBr2vOQ',
    appId: '1:255814710985:ios:b4e52de3f0b5b3a0b9bf18',
    messagingSenderId: '255814710985',
    projectId: 'journal-app-finals',
    storageBucket: 'journal-app-finals.appspot.com',
    iosBundleId: 'com.example.flutterJournalAppFinals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvy8AIrLGY7F98GxQL9KJ9q5tLbKUYgt0',
    appId: '1:255814710985:web:5e30ede1373ac496b9bf18',
    messagingSenderId: '255814710985',
    projectId: 'journal-app-finals',
    authDomain: 'journal-app-finals.firebaseapp.com',
    storageBucket: 'journal-app-finals.appspot.com',
  );
}
